### ISSUE TITLE
[BUG] Unable to boot self built fedora 38 cinnamon

### ISSUE THREAD

**Issue by mikedolx** [eupnea-linux/depthboot-builder#74]
**Describe the bug**
I have built my own fedora 38 image with cinnamon DE. I have reflashed my Chromebook `LILLIPUP` with the recovery firmware using the scritps from [mrchromebox](https://mrchromebox.tech). I have enabled the developer options, booted into guest mode and enabled the custom boot settings according to this [build-insctructions](https://eupnea-linux.github.io/docs/depthboot/build-instructions). When i plug in prepared USB flash drive and try to boot from an external drive, i get the black screen as described in the instructions. But, the Chromebook stays stuck in the black screen. The keyboard illumination stays on and that's it. I have waited for about 30 min, but nothing happened. I need to mention, that the power supply was not connected as the battery was charged about 90%. 

- The image is built using a gitlab-ci
- The image is flashed using [balena-etcher](https://www.balena.io/etcher)

**To Reproduce**
1. Build the image using the `.gitlab-ci.yml` below
2. Flash the `depthboot.img` with balena-ether on a free USB flash drive
3. Follow this [build-insctructions](https://eupnea-linux.github.io/docs/depthboot/build-instructions) to enable the developer mode and the specific boot options
4. Insert the flash drive and try to boot the Chromebook from the USB flash drive
5. Wait for the black screen to disappear

**My gitlab-ci.yaml**
```yaml
stages:
  - build

build-fedora:
  stage: build
  tags:
    - shell
    - fuchsbau
  before_script: 
    - sudo apt-get update && sudo apt-get install -y cgpt vboot-kernel-utils parted
  script:
    - |
      if [ -d depthboot-builder ]; then
        sudo rm -rf depthboot-builder
      fi
      git clone https://github.com/eupnea-linux/depthboot-builder
      cd depthboot-builder
      cp ./.github/scripts/build-image.py ./build-image.py
      sudo python3.10 ./build-image.py fedora ${VERSION} ${DE}

      echo "copying depthboot.img to /mnt/nas/Repository/Images/OS/Linux/eupnea"
      sudo cp -v depthboot.img /mnt/nas/Repository/Images/OS/Linux/eupnea/eupnea-linux_fedora_${VERSION}_${DE}.img

      cd ..
      sudo rm -rf depthboot-builder
  parallel:
    matrix:
      - VERSION:
        - 38
        - 39
        DE:
        - cinnamon
        - kde
        - gnome

```

**Full log**

Apperently i cannot paste the full log from my GitLab job, as it would exceed the comment limif of 65536 characters. It seems it also to large for pastebin..

At the end of the build there is the following error:

```shell
[Errno 1] Operation not permitted: '/mnt/depthboot/proc/fb'
Failed to build fedora + 38 + cinnamon
```
Not sure if this might be an issue. But the resulting image looks good (around 10GB large).

**Build system (please complete the following information):**
 - OS: Ubuntu Server 20.04 LTS (Proxmox Virtual Machine)

**Additional context**
- none
